#!/bin/bash
# ==============================================================================
# Script Name   : gen_gitlab_ci_fe.sh
# Description   : Frontend dynamic branch-based GitLab CI/CD pipeline generator
# Usage         : Called internally by run.sh Project Manager
# ==============================================================================

domain="$1"
pdir="$2"
target_ci="${pdir}/.gitlab-ci.yml"

# Colors & Formatting inside sourced or executed script
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'
BOLD='\033[1m'; CYAN='\033[0;36m'; NC='\033[0m'
OK="${GREEN}[✔]${NC}"; FAIL="${RED}[✘]${NC}"; WARN="${YELLOW}[⚠]${NC}"; INFO="${BLUE}[ℹ]${NC}"

echo -e "\n🦊 CẤU HÌNH PIPELINE CI/CD ĐA CHI NHÁNH CHO FRONTEND Next.js..."
echo -e "------------------------------------------------------------------------"

# Lấy danh sách các chi nhánh remote từ repository
echo -e "${INFO} Đang quét các chi nhánh từ remote git (origin)..."
git -C "$pdir" fetch --all --prune &>/dev/null || true

# Tạo mảng chứa danh sách các nhánh remote (bỏ origin/HEAD và xoá tiền tố origin/)
mapfile -t git_branches < <(git -C "$pdir" branch -r | grep -v 'origin/HEAD' | sed 's/^[[:space:]]*origin\///' | sed 's/^[[:space:]]*//' | sort -u)

if [ ${#git_branches[@]} -eq 0 ] || [ -z "${git_branches[0]}" ]; then
    echo -e "${WARN} Không tìm thấy chi nhánh remote nào hoặc thư mục không phải là git repo."
    read -p "👉 Nhập thủ công các chi nhánh muốn cấu hình (Ví dụ: develop,main): " branch_input
    branch_input=$(echo "$branch_input" | tr -d '[:space:]')
    if [ -z "$branch_input" ]; then
        echo -e "${FAIL} Danh sách chi nhánh không được để trống."
        exit 1
    fi
    IFS=',' read -r -a BRANCHES <<< "$branch_input"
else
    echo -e "\n📋 Danh sách các chi nhánh remote tìm thấy:"
    for i in "${!git_branches[@]}"; do
        echo -e "  [$(($i + 1))] ${git_branches[$i]}"
    done
    echo -e "  [m] Nhập thủ công tên chi nhánh khác..."
    
    while true; do
        read -p "👉 Chọn số tương ứng với các chi nhánh, cách nhau bằng dấu phẩy (Ví dụ: 1,2) hoặc chọn [m]: " branch_selection
        branch_selection=$(echo "$branch_selection" | tr -d '[:space:]')
        
        if [ "$branch_selection" = "m" ] || [ "$branch_selection" = "M" ]; then
            read -p "👉 Nhập thủ công các chi nhánh (Ví dụ: develop,main): " branch_input
            branch_input=$(echo "$branch_input" | tr -d '[:space:]')
            if [ -z "$branch_input" ]; then
                echo -e "${FAIL} Danh sách chi nhánh không được để trống."
                continue
            fi
            IFS=',' read -r -a BRANCHES <<< "$branch_input"
            break
        elif [ -n "$branch_selection" ]; then
            # Parse các index được chọn cách nhau bằng dấu phẩy
            IFS=',' read -r -a selected_indices <<< "$branch_selection"
            BRANCHES=()
            valid=true
            for index in "${selected_indices[@]}"; do
                if [[ "$index" =~ ^[0-9]+$ ]] && [ "$index" -ge 1 ] && [ "$index" -le "${#git_branches[@]}" ]; then
                    BRANCHES+=("${git_branches[$(($index - 1))]}")
                else
                    echo -e "${FAIL} Lựa chọn '$index' không hợp lệ."
                    valid=false
                    break
                fi
            done
            if $valid && [ ${#BRANCHES[@]} -gt 0 ]; then
                break
            fi
        else
            echo -e "${FAIL} Vui lòng nhập lựa chọn."
        fi
    done
fi

echo -e "${OK} Chi nhánh được chọn để cấu hình CI/CD: ${GREEN}$(IFS=','; echo "${BRANCHES[*]}")${NC}"

cat <<EOF > "$target_ci"
# ==============================================================================
# GitLab CI/CD Pipeline for Next.js - Auto-Generated by Star-Bash Suite
# Project: ${domain}
# Type: Frontend (Next.js / PM2)
# ==============================================================================

stages:
  - build
  - deploy

default:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
EOF

for br in "${BRANCHES[@]}"; do
    local br_upper; br_upper=$(echo "$br" | tr '[:lower:]' '[:upper:]' | tr '-' '_' | tr '/' '_')
    echo -e "\n⚙️  ${BOLD}Cấu hình cho nhánh: ${CYAN}${br}${NC}"
    
    read -p "  🔹 Nhánh '$br' có chạy bước Build không? (y/N): " has_build
    has_build=${has_build:-"n"}
    read -p "  🔹 Nhánh '$br' có chạy bước Deploy không? (y/N): " has_deploy
    has_deploy=${has_deploy:-"n"}
    
    local has_build_flag=false
    local has_deploy_flag=false
    [[ "$has_build" =~ ^[yY] ]] && has_build_flag=true
    [[ "$has_deploy" =~ ^[yY] ]] && has_deploy_flag=true
    
    if ! $has_build_flag && ! $has_deploy_flag; then
        echo -e "   ${WARN} Bỏ qua nhánh $br."
        continue
    fi
    
    if $has_build_flag; then
        cat <<EOF >> "$target_ci"

# --- BUILD JOB CHO CHI NHÁNH: ${br} ---
build-${br}:
  stage: build
  image: node:20-alpine
  rules:
    - if: \$CI_COMMIT_BRANCH == "${br}"
  variables:
    ENV_FILE: \$ENV_LOCAL_${br_upper}
  script:
    - echo "==> Khởi tạo môi trường cho chi nhánh ${br}..."
    - cp "\$ENV_FILE" .env.local
    - npm install --cache .npm --prefer-offline
    - npm run build
    - echo "==> Dọn dẹp cache biên dịch để giảm kích thước tệp nén..."
    - rm -rf .next/cache
  artifacts:
    name: "${br}-build-\$CI_COMMIT_REF_SLUG"
    expire_in: 3 days
    paths:
      - .next/
      - public/
      - package.json
      - package-lock.json
      - ecosystem.config.js
      - .env.local
EOF
    fi
    
    if $has_deploy_flag; then
        local deploy_dir="/home/${domain}"
        cat <<EOF >> "$target_ci"

# --- DEPLOY JOB CHO CHI NHÁNH: ${br} ---
deploy-${br}:
  stage: deploy
  image: alpine:latest
  rules:
    - if: \$CI_COMMIT_BRANCH == "${br}"
EOF
        if $has_build_flag; then
            cat <<EOF >> "$target_ci"
  dependencies:
    - build-${br}
EOF
        fi
        
        cat <<EOF >> "$target_ci"
  before_script:
    - apk add --no-cache openssh-client tar
    - mkdir -p ~/.ssh
    - eval \$(ssh-agent -s)
    - echo "\$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "==> Bắt đầu đóng gói tệp tin đã biên dịch..."
    - tar -czf build.tar.gz .next public package.json package-lock.json ecosystem.config.js .env.local
    
    - echo "==> Đang tải gói build lên thư mục deploy trên VPS..."
    - scp build.tar.gz deployer@\$VPS_IP:${deploy_dir}/
    
    - echo "==> Giải nén, cài đặt thư viện production và ra lệnh PM2 khởi động lại..."
    - ssh deployer@\$VPS_IP "
        cd ${deploy_dir}/ &&
        tar -xzf build.tar.gz &&
        rm -f build.tar.gz &&
        export PATH=\\\$PATH:/usr/bin:/usr/local/bin &&
        npm install --omit=dev --prefer-offline --no-audit --ignore-scripts &&
        pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
      "
    - echo "✅ Deploy thành công lên thư mục ${deploy_dir}."
EOF
    fi
done

chown deployer:deployer "$target_ci" 2>/dev/null || true
echo -e "\n${OK} Đã tạo cấu hình GitLab CI/CD đa chi nhánh động thành công tại: ${BOLD}${target_ci}${NC}"
echo -e " 🔹 Thư mục deploy cố định: ${BOLD}/home/${domain}${NC}"
