#!/bin/bash
# ==============================================================================
# Script Name   : gen_gitlab_ci.sh
# Description   : Interactive GitLab CI/CD & PM2 Configuration Generator for VPS
# Author        : Antigravity AI
# Version       : 1.0.0
# Compatibility : Ubuntu, Debian
# Usage         : sudo bash gen_gitlab_ci.sh
# ==============================================================================

set -euo pipefail

# Define Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Status Icons
TICK="${GREEN}[✔]${NC}"
CROSS="${RED}[✘]${NC}"
WARN="${YELLOW}[⚠]${NC}"
INFO="${BLUE}[ℹ]${NC}"

# Ensure script is run with root/sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}${BOLD}Lỗi:${NC} Script này phải chạy dưới quyền ${BOLD}root${NC} (sudo)."
    exit 1
fi

clear
echo -e "${BOLD}${CYAN}========================================================================${NC}"
echo -e "       🦊 TRÌNH TỰ ĐỘNG CẤU HÌNH CI-CD & PM2 CHO DỰ ÁN VPS 🦊           "
echo -e "${BOLD}${CYAN}========================================================================${NC}"
echo -e "${INFO} Quét các thư mục dự án đang có sẵn tại thư mục gốc /home..."

# Quét các thư mục dự án Next.js tại /home
APPS=()
for dir in /home/*; do
    if [ -d "$dir" ] && [ "$(basename "$dir")" != "gitlab-runner" ] && [ "$(basename "$dir")" != "security_audit" ]; then
        APPS+=("$(basename "$dir")")
    fi
done

if [ ${#APPS[@]} -eq 0 ]; then
    echo -e "${CROSS} Không phát hiện thư mục dự án nào tại /home!"
    exit 1
fi

echo -e "\n${BOLD}${WHITE}Danh sách các dự án khả dụng trên VPS:${NC}"
for i in "${!APPS[@]}"; do
    echo -e "  [$(($i+1))] 📂 ${BOLD}${APPS[$i]}${NC}"
done
echo -e ""

# Lựa chọn dự án
app_choice=""
while true; do
    read -p "👉 Chọn số tương ứng với dự án muốn cấu hình CI/CD [1-${#APPS[@]}]: " app_num
    if [[ "$app_num" =~ ^[0-9]+$ ]] && [ "$app_num" -ge 1 ] && [ "$app_num" -le ${#APPS[@]} ]; then
        app_choice="${APPS[$(($app_num-1))]}"
        break
    else
        echo -e "${CROSS} ${RED}Lựa chọn không hợp lệ! Vui lòng nhập số từ 1 đến ${#APPS[@]}.${NC}"
    fi
done

APP_PATH="/home/${app_choice}"
echo -e "\n${TICK} Bạn đã chọn dự án: ${BOLD}${app_choice}${NC} (Đường dẫn: ${APP_PATH})"

# Nhập cổng (Port) ứng dụng chạy thực tế
app_port=""
while true; do
    read -p "👉 Nhập cổng chạy Node.js/Next.js của dự án này (Ví dụ: 3000, 3008): " app_port
    if [[ "$app_port" =~ ^[0-9]+$ ]] && [ "$app_port" -gt 1024 ] && [ "$app_port" -lt 65535 ]; then
        break
    else
        echo -e "${CROSS} ${RED}Cổng không hợp lệ! Vui lòng nhập số từ 1024 đến 65535.${NC}"
    fi
done

# ==============================================================================
# 1. SINH CẤU HÌNH ECOSYSTEM.CONFIG.JS CHO PM2
# ==============================================================================
ECO_FILE="${APP_PATH}/ecosystem.config.js"
echo -e "\n${BOLD}${WHITE}==> 1. Thiết lập tệp tin cấu hình PM2 (ecosystem.config.js)${NC}"

# Tạo config ecosystem.config.js mẫu tối ưu Cluster Mode
cat << EOF > "$ECO_FILE"
module.exports = {
  apps: [
    {
      name: "${app_choice}",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      instances: "max",        // Chạy tối đa số nhân CPU khả dụng
      exec_mode: "cluster",    // Chế độ Cluster giúp zero-downtime reload
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: ${app_port}
      }
    }
  ]
};
EOF

# Phân quyền cho deployer sở hữu
chown deployer:deployer "$ECO_FILE"
echo -e "${TICK} Đã sinh cấu hình PM2 Cluster Mode thành công tại: ${BOLD}${ECO_FILE}${NC}"

# ==============================================================================
# 2. SINH CẤU HÌNH .GITLAB-CI.YML BẢO MẬT TỐI ƯU
# ==============================================================================
CI_FILE="${APP_PATH}/.gitlab-ci.yml"
echo -e "\n${BOLD}${WHITE}==> 2. Thiết lập tệp tin GitLab CI/CD Pipeline (.gitlab-ci.yml)${NC}"

cat << EOF > "$CI_FILE"
# ==============================================================================
# GitLab CI/CD Pipeline for Next.js - Auto-Generated by Star-Bash Suite
# Project: ${app_choice}
# Stages: Build -> Deploy (Non-root SSH Deploy to VPS)
# ==============================================================================

stages:
  - build
  - deploy

default:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

# ==============================================================================
# STAGE 1: BUILD STAGE (Runs in Runner Docker Container Sandbox)
# ==============================================================================
build-staging:
  stage: build
  image: node:20-alpine
  rules:
    - if: \$CI_COMMIT_BRANCH == "develop"
  variables:
    ENV_FILE: \$ENV_LOCAL_STAGING
  script:
    - echo "==> Khởi tạo môi trường Staging..."
    - cp "\$ENV_FILE" .env.local
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - npm prune --production
  artifacts:
    name: "staging-build-\$CI_COMMIT_REF_SLUG"
    expire_in: 3 days
    paths:
      - .next/
      - public/
      - node_modules/
      - package.json
      - ecosystem.config.js
      - .env.local

build-production:
  stage: build
  image: node:20-alpine
  rules:
    - if: \$CI_COMMIT_BRANCH == "main"
  variables:
    ENV_FILE: \$ENV_LOCAL_PRODUCTION
  script:
    - echo "==> Khởi tạo môi trường Production..."
    - cp "\$ENV_FILE" .env.local
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - npm prune --production
  artifacts:
    name: "production-build-\$CI_COMMIT_REF_SLUG"
    expire_in: 7 days
    paths:
      - .next/
      - public/
      - node_modules/
      - package.json
      - ecosystem.config.js
      - .env.local

# ==============================================================================
# STAGE 2: DEPLOY STAGES (SSH Non-Root to VPS Host)
# ==============================================================================
deploy-staging:
  stage: deploy
  image: alpine:latest
  rules:
    - if: \$CI_COMMIT_BRANCH == "develop"
  dependencies:
    - build-staging
  before_script:
    - apk add --no-cache openssh-client tar
    - mkdir -p ~/.ssh
    - eval \$(ssh-agent -s)
    - echo "\$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "==> Nén gói build..."
    - tar -czf build.tar.gz .next public node_modules package.json ecosystem.config.js .env.local
    - echo "==> Đẩy gói build lên VPS..."
    - scp build.tar.gz deployer@\$VPS_IP:${APP_PATH}/
    - echo "==> Giải nén và PM2 reload..."
    - ssh deployer@\$VPS_IP "
        cd ${APP_PATH}/ &&
        tar -xzf build.tar.gz &&
        rm -f build.tar.gz &&
        export PATH=\\\$PATH:/usr/bin:/usr/local/bin &&
        pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
      "
    - echo "✅ Deploy lên môi trường STAGING thành công!"

deploy-production:
  stage: deploy
  image: alpine:latest
  rules:
    - if: \$CI_COMMIT_BRANCH == "main"
  dependencies:
    - build-production
  before_script:
    - apk add --no-cache openssh-client tar
    - mkdir -p ~/.ssh
    - eval \$(ssh-agent -s)
    - echo "\$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "==> Nén gói build..."
    - tar -czf build.tar.gz .next public node_modules package.json ecosystem.config.js .env.local
    - echo "==> Đẩy gói build lên VPS..."
    - scp build.tar.gz deployer@\$VPS_IP:${APP_PATH}/
    - echo "==> Giải nén và PM2 reload..."
    - ssh deployer@\$VPS_IP "
        cd ${APP_PATH}/ &&
        tar -xzf build.tar.gz &&
        rm -f build.tar.gz &&
        export PATH=\\\$PATH:/usr/bin:/usr/local/bin &&
        pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
      "
    - echo "✅ Deploy lên môi trường PRODUCTION thành công!"
EOF

# Phân quyền cho deployer sở hữu
chown deployer:deployer "$CI_FILE"
echo -e "${TICK} Đã sinh cấu hình GitLab CI/CD thành công tại: ${BOLD}${CI_FILE}${NC}"

# ==============================================================================
# 3. PHÂN QUYỀN THƯ MỤC CHO USER DEPLOYER
# ==============================================================================
echo -e "\n${BOLD}${WHITE}==> 3. Cấu hình phân quyền hệ thống cho user 'deployer'${NC}"
chown -R deployer:deployer "${APP_PATH}"
chmod -R 755 "${APP_PATH}"
echo -e "${TICK} Đã chuyển giao toàn bộ quyền sở hữu thư mục dự án cho user ${BOLD}deployer${NC}."

echo -e "\n${BOLD}${GREEN}========================================================================${NC}"
echo -e "       🎉 THIẾT LẬP HOÀN TẤT DỰ ÁN: ${app_choice} 🎉"
echo -e "${BOLD}${GREEN}========================================================================${NC}"
echo -e " 1. ${BOLD}Cấu hình CI/CD đã tự động chèn vào thư mục dự án:${NC}"
echo -e "    - Tệp cấu hình PM2: ${BOLD}${ECO_FILE}${NC}"
echo -e "    - Tệp GitLab CI/CD: ${BOLD}${CI_FILE}${NC}"
echo -e ""
echo -e " 2. ${BOLD}LƯU Ý CỰC KỲ QUAN TRỌNG VỀ PM2:${NC}"
echo -e "    Hiện tại các tiến trình PM2 của bạn có thể đang chạy dưới quyền ${RED}root${NC}."
echo -e "    Để đảm bảo bảo mật và CI/CD tự reload thành công, hãy chạy các lệnh sau:"
echo -e "    "
echo -e "    - Bước A: Xóa tiến trình cũ của root:"
echo -e "      ${BOLD}pm2 delete ${app_choice}${NC} (hoặc ${BOLD}pm2 delete all${NC})"
echo -e "    - Bước B: Đăng nhập vào user deployer và khởi động lại dự án:"
echo -e "      ${BOLD}su - deployer${NC}"
echo -e "      ${BOLD}cd ${APP_PATH} && pm2 start ecosystem.config.js && pm2 save${NC}"
echo -e "========================================================================${NC}\n"
