#!/bin/bash
# ==============================================================================
# Script Name   : gen_gitlab_ci.sh
# Description   : Interactive GitLab CI/CD & PM2 Configuration Generator for VPS
# Author        : Antigravity AI
# Version       : 1.0.0
# Compatibility : Ubuntu, Debian
# Usage         : sudo bash gen_gitlab_ci.sh
# ==============================================================================

set -euo pipefail

# Define Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# Status Icons
TICK="${GREEN}[✔]${NC}"
CROSS="${RED}[✘]${NC}"
WARN="${YELLOW}[⚠]${NC}"
INFO="${BLUE}[ℹ]${NC}"

# Ensure script is run with root/sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}${BOLD}Lỗi:${NC} Script này phải chạy dưới quyền ${BOLD}root${NC} (sudo)."
    exit 1
fi

clear
echo -e "${BOLD}${CYAN}========================================================================${NC}"
echo -e "       🦊 TRÌNH TỰ ĐỘNG CẤU HÌNH CI-CD & PM2 CHO DỰ ÁN VPS 🦊           "
echo -e "${BOLD}${CYAN}========================================================================${NC}"
echo -e "${INFO} Quét các thư mục dự án đang có sẵn tại thư mục gốc /home..."

# Quét các thư mục dự án Next.js tại /home
APPS=()
for dir in /home/*; do
    if [ -d "$dir" ] && [ "$(basename "$dir")" != "gitlab-runner" ] && [ "$(basename "$dir")" != "security_audit" ]; then
        APPS+=("$(basename "$dir")")
    fi
done

if [ ${#APPS[@]} -eq 0 ]; then
    echo -e "${CROSS} Không phát hiện thư mục dự án nào tại /home!"
    exit 1
fi

echo -e "\n${BOLD}${WHITE}Danh sách các dự án khả dụng trên VPS:${NC}"
for i in "${!APPS[@]}"; do
    echo -e "  [$(($i+1))] 📂 ${BOLD}${APPS[$i]}${NC}"
done
echo -e ""

# Lựa chọn dự án
app_choice=""
while true; do
    read -p "👉 Chọn số tương ứng với dự án muốn cấu hình CI/CD [1-${#APPS[@]}]: " app_num
    if [[ "$app_num" =~ ^[0-9]+$ ]] && [ "$app_num" -ge 1 ] && [ "$app_num" -le ${#APPS[@]} ]; then
        app_choice="${APPS[$(($app_num-1))]}"
        break
    else
        echo -e "${CROSS} ${RED}Lựa chọn không hợp lệ! Vui lòng nhập số từ 1 đến ${#APPS[@]}.${NC}"
    fi
done

APP_PATH="/home/${app_choice}"
echo -e "\n${TICK} Bạn đã chọn dự án: ${BOLD}${app_choice}${NC} (Đường dẫn: ${APP_PATH})"

ECO_FILE="${APP_PATH}/ecosystem.config.js"
write_eco="y"

if [ -f "$ECO_FILE" ]; then
    echo -e "${WARN} Phát hiện tệp tin ${BOLD}ecosystem.config.js${NC} đã tồn tại sẵn trong dự án."
    read -p "❓ Bạn có muốn ghi đè bằng cấu hình Cluster Mode tối ưu mới không? (y/N): " overwrite_eco
    overwrite_eco=${overwrite_eco:-"n"}
    if [[ ! "$overwrite_eco" =~ ^[yY] ]]; then
        write_eco="n"
    fi
fi

# Nhập cổng (Port) ứng dụng chạy thực tế - CHỈ hỏi nếu cần ghi mới/ghi đè cấu hình PM2
app_port=""
if [ "$write_eco" = "y" ]; then
    while true; do
        read -p "👉 Nhập cổng chạy Node.js/Next.js của dự án này (Ví dụ: 3000, 3008): " app_port
        if [[ "$app_port" =~ ^[0-9]+$ ]] && [ "$app_port" -gt 1024 ] && [ "$app_port" -lt 65535 ]; then
            break
        else
            echo -e "${CROSS} ${RED}Cổng không hợp lệ! Vui lòng nhập số từ 1024 đến 65535.${NC}"
        fi
    done
fi

# ==============================================================================
# 1. SINH CẤU HÌNH ECOSYSTEM.CONFIG.JS CHO PM2
# ==============================================================================
echo -e "\n${BOLD}${WHITE}==> 1. Thiết lập tệp tin cấu hình PM2 (ecosystem.config.js)${NC}"

if [ "$write_eco" = "y" ]; then
    # Tạo config ecosystem.config.js mẫu tối ưu Cluster Mode
    cat << EOF > "$ECO_FILE"
module.exports = {
  apps: [
    {
      name: "${app_choice}",
      script: "node_modules/next/dist/bin/next",
      args: "start",
      instances: "max",        // Chạy tối đa số nhân CPU khả dụng
      exec_mode: "cluster",    // Chế độ Cluster giúp zero-downtime reload
      watch: false,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: ${app_port}
      }
    }
  ]
};
EOF
    echo -e "${TICK} Đã sinh cấu hình PM2 Cluster Mode thành công tại: ${BOLD}${ECO_FILE}${NC}"
else
    echo -e "${TICK} Giữ nguyên tệp cấu hình ${BOLD}ecosystem.config.js${NC} hiện tại của bạn."
fi

# Phân quyền cho deployer sở hữu
chown deployer:deployer "$ECO_FILE"

# ==============================================================================
# 2. SINH CẤU HÌNH .GITLAB-CI.YML BẢO MẬT TỐI ƯU
# ==============================================================================
CI_FILE="${APP_PATH}/.gitlab-ci.yml"
echo -e "\n${BOLD}${WHITE}==> 2. Thiết lập tệp tin GitLab CI/CD Pipeline (.gitlab-ci.yml)${NC}"

cat << EOF > "$CI_FILE"
# ==============================================================================
# GitLab CI/CD Pipeline for Next.js - Auto-Generated by Star-Bash Suite
# Project: ${app_choice}
# Method: Direct VPS Pull & Build (Bypasses Runner Artifacts, Zero HTTP 413 Errors)
# ==============================================================================

stages:
  - deploy

# ==============================================================================
# DEPLOY STAGES (SSH Non-Root to VPS Host)
# ==============================================================================
deploy-staging:
  stage: deploy
  image: alpine:latest
  rules:
    - if: \$CI_COMMIT_BRANCH == "develop"
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - eval \$(ssh-agent -s)
    - echo "\$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "==> Đồng bộ tệp cấu hình .env.local sang VPS..."
    - scp \$ENV_LOCAL_STAGING deployer@\$VPS_IP:${APP_PATH}/.env.local
    
    - echo "==> Thực hiện Git Pull, cài đặt và Build trực tiếp trên VPS..."
    - ssh deployer@\$VPS_IP "
        cd ${APP_PATH}/ &&
        git fetch origin develop &&
        git reset --hard origin/develop &&
        export PATH=\\\$PATH:/usr/bin:/usr/local/bin &&
        npm install --prefer-offline --no-audit &&
        npm run build &&
        pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
      "
    - echo "✅ Deploy lên môi trường STAGING thành công!"

deploy-production:
  stage: deploy
  image: alpine:latest
  rules:
    - if: \$CI_COMMIT_BRANCH == "main"
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - eval \$(ssh-agent -s)
    - echo "\$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "==> Đồng bộ tệp cấu hình .env.local sang VPS..."
    - scp \$ENV_LOCAL_PRODUCTION deployer@\$VPS_IP:${APP_PATH}/.env.local
    
    - echo "==> Thực hiện Git Pull, cài đặt và Build trực tiếp trên VPS..."
    - ssh deployer@\$VPS_IP "
        cd ${APP_PATH}/ &&
        git fetch origin main &&
        git reset --hard origin/main &&
        export PATH=\\\$PATH:/usr/bin:/usr/local/bin &&
        npm install --prefer-offline --no-audit &&
        npm run build &&
        pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js
      "
    - echo "✅ Deploy lên môi trường PRODUCTION thành công!"
EOF

# Phân quyền cho deployer sở hữu
chown deployer:deployer "$CI_FILE"
echo -e "${TICK} Đã sinh cấu hình GitLab CI/CD thành công tại: ${BOLD}${CI_FILE}${NC}"

# ==============================================================================
# 3. PHÂN QUYỀN THƯ MỤC CHO USER DEPLOYER
# ==============================================================================
echo -e "\n${BOLD}${WHITE}==> 3. Cấu hình phân quyền hệ thống cho user 'deployer'${NC}"
chown -R deployer:deployer "${APP_PATH}"
chmod -R 755 "${APP_PATH}"
echo -e "${TICK} Đã chuyển giao toàn bộ quyền sở hữu thư mục dự án cho user ${BOLD}deployer${NC}."

echo -e "\n${BOLD}${GREEN}========================================================================${NC}"
echo -e "       🎉 THIẾT LẬP HOÀN TẤT DỰ ÁN: ${app_choice} 🎉"
echo -e "${BOLD}${GREEN}========================================================================${NC}"
echo -e " 1. ${BOLD}Cấu hình CI/CD đã tự động chèn vào thư mục dự án:${NC}"
echo -e "    - Tệp cấu hình PM2: ${BOLD}${ECO_FILE}${NC}"
echo -e "    - Tệp GitLab CI/CD: ${BOLD}${CI_FILE}${NC}"
echo -e ""
echo -e " 2. ${BOLD}LƯU Ý CỰC KỲ QUAN TRỌNG VỀ PM2:${NC}"
echo -e "    Hiện tại các tiến trình PM2 của bạn có thể đang chạy dưới quyền ${RED}root${NC}."
echo -e "    Để đảm bảo bảo mật và CI/CD tự reload thành công, hãy chạy các lệnh sau:"
echo -e "    "
echo -e "    - Bước A: Xóa tiến trình cũ của root:"
echo -e "      ${BOLD}pm2 delete ${app_choice}${NC} (hoặc ${BOLD}pm2 delete all${NC})"
echo -e "    - Bước B: Đăng nhập vào user deployer và khởi động lại dự án:"
echo -e "      ${BOLD}su - deployer${NC}"
echo -e "      ${BOLD}cd ${APP_PATH} && pm2 start ecosystem.config.js && pm2 save${NC}"
echo -e "========================================================================${NC}\n"
